### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by sb37** [jgaalen/domoticz-wellbeing-plugin#3]
According to https://github.com/JohNan/homeassistant-wellbeing/issues/99 logins made using the "old" API are rejected.

(The plugin has been working for a year now. Great!)

**Comment by jgaalen** [comment]
> According to [JohNan/homeassistant-wellbeing#99](https://github.com/JohNan/homeassistant-wellbeing/issues/99) logins made using the "old" API are rejected.
> 
> (The plugin has been working for a year now. Great!)

I'm in the process of making an update to work with the new API. I'm just stuck because I was stupid and disabled my API Key, but can't enable it nor I can create a new one. Waiting for support...

**Comment by jgaalen** [comment]
Massive update using the new APIs. I've put some effort in keeping the normal username/password which is a lot more convenient then needing to create an api key and refresh token yourself. I think this would be more stable as a refresh token is expired as soon as it's used, so storing it in the hardware field makes no sense

**Comment by sb37** [comment]
Works like a charm.
I had some funny errors in the log. I deleted all the "old" devices started again. No more errors. Everything works.
